Llama-3.2-1B-Instruct:
  - meta-llama/Llama-3.2-1B-Instruct
#  - google/gemma-3-1b-it
#  - FuseAI/FuseChat-Llama-3.2-3B-Instruct
Llama-3.2-3B-Instruct:
  - meta-llama/Llama-3.2-3B-Instruct
Llama-3.2-3B:
   - meta-llama/Llama-3.2-3B


gemma-3-4b-it:
  - google/gemma-3-4b-it
#  - google/gemma-3-1b-it
#  - meta-llama/Llama-3.2-3B-Instruct
#  - meta-llama/Llama-3.2-1B-Instruct

gemma-3-1b-it:
  - google/gemma-3-1b-it
#  - meta-llama/Llama-3.2-1B-Instruct

gemma-7b-it:
  - google/gemma-7b-it  n

llama-2-13b:
  - unsloth/llama-2-13b
  - layoric/llama-2-13b-code-alpaca
  - vanillaOVO/WizardMath-13B-V1.0
  - WizardLMTeam/WizardLM-13B-V1.2

test_4b_models:
    - meta-llama/Llama-3.2-3B-Instruct

qwen_models:
  - Qwen/Qwen2.5-1.5B-Instruct




